#!/usr/bin/env zsh

# DEPENDENCY
#
type jwtgen &>/dev/null
if [[ $? -eq 1 ]]; then
    echo "Dependency not met: jwtgen.\n(Try: $ npm install -g jwtgen)"
    return
fi

# USAGE
#
if [[ $# -ne 2 ]]; then
    script=$(echo $0 | awk -F'/' '{print $NF}')
    echo "Usage:" $script "<user_id> <secret>"
    exit
fi

# GET UTC
#
IAT=$(date -j -f "%a %b %d %T %Z %Y" "$(date)" "+%s")

# GENERATE TOKEN
#
token=$(jwtgen -a HS256 -c UID=$1 -i $IAT -s $2)
if [[ $? -eq 1 ]]; then
    echo "Error: jwtgen failed."
    return
fi

type pbcopy &>/dev/null
if [[ $? -eq 0 ]]; then
    echo $token | pbcopy
    if [[ $? -eq 1 ]]; then
        echo "Error: Could not copy to clipboard."
    else
        echo "Copied to clipboard."
    fi
    return
fi

type clip.exe &>/dev/null
if [[ $? -eq 0 ]]; then
    echo $token | clip.exe
    if [[ $? -eq 1 ]]; then
        echo "Error: Could not copy to clipboard."
    else
        echo "Copied to clipboard."
    fi
    return
fi

echo "Warning: Could not access clipboard."
echo "Token:" $token
